apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployment-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins     # or 'default' if that's what your Jenkins pod uses
  namespace: default
roleRef:
  kind: Role
  name: jenkins-deployment-manager
  apiGroup: rbac.authorization.k8s.io

